"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient


class AgentClient:
    """Agent registry — register and manage agent images"""

    def __init__(self, http: HttpClient):
        self._http = http

    def register(self, **kwargs) -> dict:
        """Register a new agent in the catalog"""
        resp = self._http.post("/registry/v1/agents", json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def list(self) -> dict:
        """List agents with optional filters"""
        resp = self._http.get("/registry/v1/agents")
        resp.raise_for_status()
        return resp.json()

    def get(self, id: str) -> dict:
        """Get agent by ID"""
        resp = self._http.get("/registry/v1/agents/{id}".replace("{id}", id))
        resp.raise_for_status()
        return resp.json()

    def update(self, id: str, **kwargs) -> dict:
        """Update agent fields"""
        resp = self._http.put("/registry/v1/agents/{id}".replace("{id}", id), json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def delete(self, id: str) -> None:
        """Delete agent by ID"""
        resp = self._http.delete("/registry/v1/agents/{id}".replace("{id}", id))
        resp.raise_for_status()

    def search(self) -> dict:
        """Find agents matching given capabilities"""
        resp = self._http.get("/registry/v1/agents/search")
        resp.raise_for_status()
        return resp.json()
