"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient
from hexel._internal.ws import WSConnection


class SandboxClient:
    """Isolated execution environments"""

    def __init__(self, http: HttpClient):
        self._http = http

    def create(self, **kwargs) -> dict:
        """Allocates a VM from the pool or creates a new one for the requesting org"""
        resp = self._http.post("/compute/v1/vms/allocate", json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def list(self) -> dict:
        """Returns VMs scoped to the caller's org"""
        resp = self._http.get("/compute/v1/vms")
        resp.raise_for_status()
        data = resp.json()
        return data if isinstance(data, list) else data.get("agents", data.get("items", []))

    def get(self, id: str) -> dict:
        """Get Agent VM by ID"""
        resp = self._http.get("/compute/v1/vms/{id}".replace("{id}", id))
        resp.raise_for_status()
        return resp.json()

    def delete(self, id: str) -> None:
        """Delete Agent VM"""
        resp = self._http.delete("/compute/v1/vms/{id}".replace("{id}", id))
        resp.raise_for_status()

    def release(self, id: str, **kwargs) -> dict:
        """Release Agent VM"""
        resp = self._http.post("/compute/v1/vms/{id}/release".replace("{id}", id), json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def renew(self, id: str, **kwargs) -> dict:
        """Renew Agent VM TTL"""
        resp = self._http.post("/compute/v1/vms/{id}/renew".replace("{id}", id), json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def execute(self, id: str) -> None:
        """Runs code or shell commands in an allocated sandbox VM"""
        resp = self._http.post("/compute/v1/vms/{id}/execute".replace("{id}", id))
        resp.raise_for_status()
