"""Generated by hexel-sdk-generator. Do not edit manually."""
from hexel.compute._sandbox import SandboxClient
from hexel.compute._agent import AgentClient
from hexel.compute._instance import InstanceClient

__all__ = ["ComputeClient", "SandboxClient", "AgentClient", "InstanceClient"]


class ComputeClient:
    """Hexel Compute — deploy agents and run sandboxes."""

    def __init__(self, compute_http, registry_http=None):
        self.sandbox = SandboxClient(compute_http)
        self.agent = AgentClient(registry_http or compute_http)
        self.instance = InstanceClient(compute_http)
