"""Generated by hexel-sdk-generator. Do not edit manually."""
from hexel.compute._sandbox import SandboxClient
from hexel.compute._agent import AgentClient
from hexel.compute._instance import InstanceClient

__all__ = ["ComputeClient", "SandboxClient", "AgentClient", "InstanceClient"]


class ComputeClient:
    """Hexel Compute — deploy agents and run sandboxes."""

    def __init__(self, http):
        self.sandbox = SandboxClient(http)
        self.agent = AgentClient(http)
        self.instance = InstanceClient(http)
