"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient


class InstanceClient:
    """Agent deployments — deploy agents and manage instances"""

    def __init__(self, http: HttpClient):
        self._http = http

    def deploy(self, agent_id: str) -> dict:
        """Creates a new deployment from a registered agent. Returns a deployment_id to use for all subsequent operations."""
        resp = self._http.post("/compute/v1/agents/{agent_id}/deploy".replace("{agent_id}", agent_id))
        resp.raise_for_status()
        return resp.json()

    def list(self) -> dict:
        """List all deployments"""
        resp = self._http.get("/compute/v1/deployments")
        resp.raise_for_status()
        data = resp.json()
        return data if isinstance(data, list) else data.get("agents", data.get("items", []))

    def get(self, deployment_id: str) -> dict:
        """Get deployment by ID"""
        resp = self._http.get("/compute/v1/deployments/{deployment_id}".replace("{deployment_id}", deployment_id))
        resp.raise_for_status()
        return resp.json()

    def delete(self, deployment_id: str) -> None:
        """Delete a deployment"""
        resp = self._http.delete("/compute/v1/deployments/{deployment_id}".replace("{deployment_id}", deployment_id))
        resp.raise_for_status()

    def stop(self, deployment_id: str) -> dict:
        """Stop a deployment"""
        resp = self._http.post("/compute/v1/deployments/{deployment_id}/stop".replace("{deployment_id}", deployment_id))
        resp.raise_for_status()
        return resp.json()

    def redeploy(self, deployment_id: str) -> dict:
        """Redeploy (stop + start)"""
        resp = self._http.post("/compute/v1/deployments/{deployment_id}/redeploy".replace("{deployment_id}", deployment_id))
        resp.raise_for_status()
        return resp.json()
