"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
import time
import threading
from hexel._internal.http import HttpClient
from hexel._internal.ws import WSConnection


class SandboxClient:
    """Isolated execution environments"""

    def __init__(self, http: HttpClient):
        self._http = http
        self._connections: dict[str, WSConnection] = {}
        self._vm_cache: dict[str, dict] = {}
        self._connecting: dict[str, threading.Thread] = {}

    def create(self, **kwargs) -> dict:
        """Allocates a sandbox VM. WS connects in background."""
        resp = self._http.post("/compute/v1/vms/allocate", json=kwargs)
        resp.raise_for_status()
        data = resp.json()
        self._vm_cache[data["vm_id"]] = data
        # Fire WS connect in background immediately
        bearer = self._http._auth.token
        t = threading.Thread(target=self._bg_connect, args=(data["vm_id"], data["ws_url"], bearer), daemon=True)
        t.start()
        self._connecting[data["vm_id"]] = t
        return data

    def _bg_connect(self, vm_id: str, ws_url: str, bearer: str):
        """Connect WS — simple retry like compute.py does."""
        for _ in range(10):
            try:
                self._connections[vm_id] = WSConnection(ws_url, bearer)
                return
            except Exception:
                time.sleep(0.2)

    def list(self) -> dict:
        resp = self._http.get("/compute/v1/vms")
        resp.raise_for_status()
        return resp.json()

    def get(self, id: str) -> dict:
        resp = self._http.get(f"/compute/v1/vms/{id}")
        resp.raise_for_status()
        return resp.json()

    def delete(self, id: str) -> None:
        self._cleanup(id)
        resp = self._http.delete(f"/compute/v1/vms/{id}")
        resp.raise_for_status()

    def release(self, id: str, **kwargs) -> dict:
        self._cleanup(id)
        resp = self._http.post(f"/compute/v1/vms/{id}/release", json=kwargs)
        if resp.status_code == 404:
            return {"id": id, "state": "terminated"}
        resp.raise_for_status()
        return resp.json()

    def renew(self, id: str, **kwargs) -> dict:
        resp = self._http.post(f"/compute/v1/vms/{id}/renew", json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def execute(self, id: str, *, code: str, language: str = "python") -> dict:
        """Execute code via persistent WebSocket."""
        conn = self._get_ws(id)
        return conn.execute(code, language)

    def run(self, id: str, command: str) -> dict:
        """Run a shell command via persistent WebSocket."""
        conn = self._get_ws(id)
        return conn.command(command)

    def _get_ws(self, id: str) -> WSConnection:
        # Wait for background connect
        t = self._connecting.pop(id, None)
        if t:
            t.join(timeout=10)
        conn = self._connections.get(id)
        if conn:
            return conn
        # Fallback: connect now
        vm = self._vm_cache.get(id) or self.get(id)
        bearer = self._http._auth.token
        for _ in range(10):
            try:
                conn = WSConnection(vm["ws_url"], bearer)
                self._connections[id] = conn
                return conn
            except Exception:
                time.sleep(0.2)
        raise ConnectionError(f"Failed to connect WS for sandbox {id}")

    def _cleanup(self, id: str):
        t = self._connecting.pop(id, None)
        if t:
            t.join(timeout=2)
        conn = self._connections.pop(id, None)
        if conn:
            conn.close()
        self._vm_cache.pop(id, None)
