"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
import time
from hexel._internal.http import HttpClient
from hexel._internal.ws import WSConnection


class SandboxClient:
    """Isolated execution environments"""

    def __init__(self, http: HttpClient):
        self._http = http
        self._connections: dict[str, WSConnection] = {}
        self._vm_cache: dict[str, dict] = {}

    def create(self, **kwargs) -> dict:
        """Allocates a VM from the pool"""
        resp = self._http.post("/compute/v1/vms/allocate", json=kwargs)
        resp.raise_for_status()
        data = resp.json()
        self._vm_cache[data["vm_id"]] = data
        return data

    def list(self) -> dict:
        resp = self._http.get("/compute/v1/vms")
        resp.raise_for_status()
        data = resp.json()
        return data if isinstance(data, list) else data.get("agents", data.get("items", []))

    def get(self, id: str) -> dict:
        resp = self._http.get("/compute/v1/vms/{id}".replace("{id}", id))
        resp.raise_for_status()
        return resp.json()

    def delete(self, id: str) -> None:
        resp = self._http.delete("/compute/v1/vms/{id}".replace("{id}", id))
        resp.raise_for_status()
        self._connections.pop(id, None)
        self._vm_cache.pop(id, None)

    def release(self, id: str, **kwargs) -> dict:
        conn = self._connections.pop(id, None)
        if conn:
            conn.close()
        self._vm_cache.pop(id, None)
        resp = self._http.post("/compute/v1/vms/{id}/release".replace("{id}", id), json=kwargs)
        if resp.status_code == 404:
            return {"id": id, "state": "terminated"}
        resp.raise_for_status()
        return resp.json()

    def renew(self, id: str, **kwargs) -> dict:
        resp = self._http.post("/compute/v1/vms/{id}/renew".replace("{id}", id), json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def execute(self, id: str, *, code: str, language: str = "python") -> dict:
        """Execute code via WebSocket (fast path ~50ms)."""
        conn = self._connections.get(id)
        if not conn:
            vm = self._vm_cache.get(id)
            ws_url = vm["ws_url"] if vm else self.get(id).get("ws_url")
            bearer = self._http._auth.token
            for attempt in range(5):
                try:
                    conn = WSConnection(ws_url, bearer)
                    self._connections[id] = conn
                    break
                except Exception:
                    if attempt == 4:
                        raise
                    time.sleep(1 + attempt)
        result = conn.execute(code, language)
        if result["status"] == "error" and "kernel" in result.get("output", "").lower():
            # Kernel cold start — reconnect and retry once
            conn.close()
            bearer = self._http._auth.token
            vm = self._vm_cache.get(id)
            ws_url = vm["ws_url"] if vm else self.get(id).get("ws_url")
            time.sleep(1)
            conn = WSConnection(ws_url, bearer)
            self._connections[id] = conn
            result = conn.execute(code, language)
        return result
