"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any

@dataclass
class OAuthClient:
    """iamclient.OAuthClient"""
    client_id: str | None = None
    created_at: str | None = None
    is_active: bool | None = None
    name: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "OAuthClient":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class OAuthClientResponse:
    """iamclient.OAuthClientResponse"""
    client_id: str | None = None
    client_secret: str | None = None
    name: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "OAuthClientResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class InstanceInfo:
    """models.Agent"""
    allowed_org_ids: list[str] | None = None
    author: str | None = None
    capabilities: list[str] | None = None
    created_at: str | None = None
    description: str | None = None
    endpoint: str | None = None
    id: str | None = None
    image: str | None = None
    image_pull_secret: models.ImagePullSecret | None = None
    manifest: models.AgentManifest | None = None
    metadata: dict[str, string] | None = None
    name: str | None = None
    org_id: str | None = None
    public_key: str | None = None
    state: str | None = None
    updated_at: str | None = None
    version: str | None = None
    visibility: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "InstanceInfo":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class SandboxInfo:
    """models.AgentVM"""
    agentd_token: str | None = None
    allocated_at: str | None = None
    created_at: str | None = None
    env: dict[str, string] | None = None
    expires_at: str | None = None
    id: str | None = None
    metadata: dict[str, string] | None = None
    org_id: str | None = None
    pod_ip: str | None = None
    pod_name: str | None = None
    released_at: str | None = None
    skills: list[str] | None = None
    state: str | None = None
    tier: str | None = None
    ttl_seconds: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "SandboxInfo":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CreateSandboxRequest:
    """models.AllocateRequest"""
    env: dict[str, string] | None = None
    metadata: dict[str, string] | None = None
    org_id: str | None = None
    secure_runtime: str | None = None
    skills: list[str] | None = None
    tier: str
    ttl_seconds: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "CreateSandboxRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class SandboxResponse:
    """models.AllocateResponse"""
    agentd_token: str | None = None
    endpoint: str | None = None
    expires_at: str | None = None
    skills_loaded: list[str] | None = None
    state: str | None = None
    tier: str | None = None
    vm_id: str | None = None
    ws_url: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "SandboxResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CreateSkillRequest:
    """models.CreateSkillRequest"""
    content: str
    description: str | None = None
    name: str
    resources: dict[str, string] | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "CreateSkillRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ErrorResponse:
    """models.ErrorResponse"""
    code: int | None = None
    message: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ErrorResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class PoolConfig:
    """models.PoolConfig"""
    default_skills: list[str] | None = None
    default_tier: str | None = None
    idle_ttl_seconds: int | None = None
    max_total: int | None = None
    max_vm_ttl_seconds: int | None = None
    max_warm: int | None = None
    min_warm: int | None = None
    recycle: bool | None = None
    scale_up_threshold: float | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "PoolConfig":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class PoolStatus:
    """models.PoolStatus"""
    allocated: int | None = None
    by_tier: dict[str, integer] | None = None
    total: int | None = None
    warm: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "PoolStatus":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ReleaseRequest:
    """models.ReleaseRequest"""
    recycle: bool | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ReleaseRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class RenewRequest:
    """models.RenewRequest"""
    ttl_seconds: int
    @classmethod
    def from_dict(cls, d: dict) -> "RenewRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class Skill:
    """models.Skill"""
    content: str | None = None
    content_hash: str | None = None
    created_at: str | None = None
    description: str | None = None
    name: str | None = None
    resources: dict[str, string] | None = None
    updated_at: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "Skill":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class UsageRecord:
    """models.UsageRecord"""
    duration_seconds: int | None = None
    ended_at: str | None = None
    reason: str | None = None
    started_at: str | None = None
    tier: str | None = None
    vm_id: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "UsageRecord":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class UsageSummary:
    """models.UsageSummary"""
    by_tier: dict[str, integer] | None = None
    org_id: str | None = None
    period_end: str | None = None
    period_start: str | None = None
    total_seconds: int | None = None
    vm_count: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "UsageSummary":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class AgentManifest:
    """models.AgentManifest"""
    authentication: dict | None = None
    capabilities: dict | None = None
    description: str | None = None
    input_schema: dict | None = None
    name: str | None = None
    output_schema: dict | None = None
    runtime: dict | None = None
    skills: list[models.ManifestSkill] | None = None
    url: str | None = None
    version: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "AgentManifest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class AgentResponse:
    """models.AgentResponse"""
    agent: models.Agent | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "AgentResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class AgentsListResponse:
    """models.AgentsListResponse"""
    agents: list[models.Agent] | None = None
    total: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "AgentsListResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CreateAgentRequest:
    """models.CreateAgentRequest"""
    author: str | None = None
    capabilities: list[str] | None = None
    description: str | None = None
    endpoint: str | None = None
    image: str
    image_pull_secret: models.ImagePullSecret | None = None
    manifest: models.AgentManifest | None = None
    metadata: dict[str, string] | None = None
    name: str
    org_id: str
    version: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "CreateAgentRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CreateToolRequest:
    """models.CreateToolRequest"""
    category: str | None = None
    description: str | None = None
    id: str
    name: str
    @classmethod
    def from_dict(cls, d: dict) -> "CreateToolRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ImagePullSecret:
    """models.ImagePullSecret"""
    password: str | None = None
    registry: str | None = None
    username: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ImagePullSecret":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ManifestSkill:
    """models.ManifestSkill"""
    id: str | None = None
    inputModes: list[str] | None = None
    outputModes: list[str] | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ManifestSkill":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class Tool:
    """models.Tool"""
    category: str | None = None
    created_at: str | None = None
    description: str | None = None
    id: str | None = None
    name: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "Tool":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ToolResponse:
    """models.ToolResponse"""
    tool: models.Tool | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ToolResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ToolsListResponse:
    """models.ToolsListResponse"""
    tools: list[models.Tool] | None = None
    total: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "ToolsListResponse":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class UpdateAgentRequest:
    """models.UpdateAgentRequest"""
    capabilities: list[str] | None = None
    description: str | None = None
    endpoint: str | None = None
    image: str | None = None
    manifest: models.AgentManifest | None = None
    metadata: dict[str, string] | None = None
    name: str | None = None
    public_key: str | None = None
    state: str | None = None
    version: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "UpdateAgentRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CodeContext:
    """models.CodeContext"""
    created_at: str | None = None
    id: str | None = None
    kernel_id: str | None = None
    language: str | None = None
    session_id: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "CodeContext":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CommandStatus:
    """models.CommandStatus"""
    exit_code: int | None = None
    finished_at: str | None = None
    id: str | None = None
    running: bool | None = None
    started_at: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "CommandStatus":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class CreateContextRequest:
    """models.CreateContextRequest"""
    language: str
    session_id: str
    @classmethod
    def from_dict(cls, d: dict) -> "CreateContextRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ExecuteCodeRequest:
    """models.ExecuteCodeRequest"""
    code: str
    context_id: str
    @classmethod
    def from_dict(cls, d: dict) -> "ExecuteCodeRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class ExecuteRequest:
    """models.ExecuteRequest"""
    @classmethod
    def from_dict(cls, d: dict) -> "ExecuteRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class FileInfo:
    """models.FileInfo"""
    group: str | None = None
    is_dir: bool | None = None
    mod_time: str | None = None
    mode: str | None = None
    owner: str | None = None
    path: str | None = None
    size: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "FileInfo":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class LoadSkillsRequest:
    """models.LoadSkillsRequest"""
    skills: list[str]
    @classmethod
    def from_dict(cls, d: dict) -> "LoadSkillsRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class MetricsSnapshot:
    """models.MetricsSnapshot"""
    cpu_percent: float | None = None
    mem_total_bytes: int | None = None
    mem_used_bytes: int | None = None
    tokens_total: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "MetricsSnapshot":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class RunCommandRequest:
    """models.RunCommandRequest"""
    background: bool | None = None
    command: str
    cwd: str | None = None
    envs: dict[str, string] | None = None
    gid: int | None = None
    timeout_ms: int | None = None
    uid: int | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "RunCommandRequest":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class SSEEvent:
    """models.SSEEvent"""
    data: str | None = None
    event: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "SSEEvent":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

@dataclass
class SkillInfo:
    """models.SkillInfo"""
    loaded: bool | None = None
    name: str | None = None
    path: str | None = None
    @classmethod
    def from_dict(cls, d: dict) -> "SkillInfo":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

