"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient


class ApprovalClient:
    """Approval workflows — review and approve agent actions"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list(self) -> dict:
        """List approval requests with optional filtering by org, agent, status, task"""
        resp = self._http.get("/v1/approvals")
        resp.raise_for_status()
        data = resp.json()
        return data if isinstance(data, list) else data.get("agents", data.get("items", []))

    def create(self, **kwargs) -> dict:
        """Create a new approval request with PENDING status and 24h expiry"""
        resp = self._http.post("/v1/approvals", json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def get(self, id: str) -> dict:
        """Retrieve a single approval request by its UUID"""
        resp = self._http.get("/v1/approvals/{id}".replace("{id}", id))
        resp.raise_for_status()
        return resp.json()

    def review(self, id: str, **kwargs) -> dict:
        """Approve or reject a pending approval request"""
        resp = self._http.post("/v1/approvals/{id}/review".replace("{id}", id), json=kwargs)
        resp.raise_for_status()
        return resp.json()

    def list_by_task(self, task_id: str) -> dict:
        """List all pending approval requests for a given task ID"""
        resp = self._http.get("/v1/tasks/{task_id}/approvals".replace("{task_id}", task_id))
        resp.raise_for_status()
        data = resp.json()
        return data if isinstance(data, list) else data.get("agents", data.get("items", []))
