"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient


class FleetClient:
    """Fleet management — create and configure agent fleets"""

    def __init__(self, http: HttpClient):
        self._http = http

    def create(self) -> dict:
        """Create fleet"""
        resp = self._http.post("/orchestrator/v1/fleets")
        resp.raise_for_status()
        return resp.json()

    def list(self) -> None:
        """List fleets"""
        resp = self._http.get("/orchestrator/v1/fleets")
        resp.raise_for_status()

    def get(self, fleet_id: str) -> dict:
        """Get fleet"""
        resp = self._http.get("/orchestrator/v1/fleets/{fleet_id}".replace("{fleet_id}", fleet_id))
        resp.raise_for_status()
        return resp.json()

    def add_agent(self, fleet_id: str) -> dict:
        """Add agent to fleet"""
        resp = self._http.post("/orchestrator/v1/fleets/{fleet_id}/agents".replace("{fleet_id}", fleet_id))
        resp.raise_for_status()
        return resp.json()

    def list_agents(self, fleet_id: str) -> None:
        """List fleet agents"""
        resp = self._http.get("/orchestrator/v1/fleets/{fleet_id}/agents".replace("{fleet_id}", fleet_id))
        resp.raise_for_status()
