"""Generated by hexel-sdk-generator. Do not edit manually."""
from __future__ import annotations
from hexel._internal.http import HttpClient


class TaskClient:
    """Task execution — submit goals, review plans, track results"""

    def __init__(self, http: HttpClient):
        self._http = http

    def create(self) -> dict:
        """Submit task"""
        resp = self._http.post("/orchestrator/v1/tasks")
        resp.raise_for_status()
        return resp.json()

    def list(self) -> None:
        """List tasks"""
        resp = self._http.get("/orchestrator/v1/tasks")
        resp.raise_for_status()

    def get(self, task_id: str) -> dict:
        """Get task"""
        resp = self._http.get("/orchestrator/v1/tasks/{task_id}".replace("{task_id}", task_id))
        resp.raise_for_status()
        return resp.json()

    def update_status(self, task_id: str) -> None:
        """Update task status"""
        resp = self._http.put("/orchestrator/v1/tasks/{task_id}/status".replace("{task_id}", task_id))
        resp.raise_for_status()

    def approve_plan(self, task_id: str) -> dict:
        """Approve plan"""
        resp = self._http.post("/orchestrator/v1/tasks/{task_id}/plan/approve".replace("{task_id}", task_id))
        resp.raise_for_status()
        return resp.json()

    def reject_plan(self, task_id: str) -> dict:
        """Reject plan"""
        resp = self._http.post("/orchestrator/v1/tasks/{task_id}/plan/reject".replace("{task_id}", task_id))
        resp.raise_for_status()
        return resp.json()

    def stream(self, task_id: str) -> None:
        """Stream task execution events"""
        resp = self._http.get("/orchestrator/v1/tasks/{task_id}/stream".replace("{task_id}", task_id))
        resp.raise_for_status()
